version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lendinvest-app
    volumes:
      -  ./code:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: lendinvest-nginx
    ports:
      - "8000:80"
    volumes:
      - ./code:/var/www
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge